/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'walterg2' at '3/6/14 9:32 PM' with Gradle 1.10
 *
 * @author walterg2, @date 3/6/14 9:32 PM
 */

import spock.lang.Specification

class RomanNumeralSpec extends Specification {

	def 'RomanNumerals can translate 1 to Roman'() {
		given:
		def romanNumeral = new RomanNumeral()

		when:
		def result = romanNumeral.translate(1)

		then:
		result == 'I'
	}
}
