/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'walterg2' at '3/6/14 9:32 PM' with Gradle 1.10
 *
 * @author walterg2, @date 3/6/14 9:32 PM
 */
class RomanNumeral {
    def translate(def number) {
    	'I'
    }
}
