/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'walterg2' at '3/6/14 9:32 PM' with Gradle 1.10
 *
 * @author walterg2, @date 3/6/14 9:32 PM
 */
class RomanNumeral {

	def ARABIC_TO_ROMAN = [
    40 : 'XL',
    10 : 'X',
    9 : 'IX',
    5 : 'V',
    4 : 'IV',
    1 : 'I'
	]

    def translate(def number) {
      def result = ''
    	ARABIC_TO_ROMAN.each {
        while (number > it.key - 1) {
          result += it.value
          number -= it.key
        }
      }

      result
    }
}
